trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

variables:
   APP_NAME: 'config-pilot-job'
steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  displayName: 'Installing go dependencies'
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: 'Building application' 
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: InstallSSHKey@0
  displayName: 'ssh key installation'
  inputs:
    hostName: 'vs-ssh.visualstudio.com'
    sshPublicKey: '$(SSH_ID_PUBKEY)'
    sshKeySecureFile: 'ssh_id_rsa'

- script: |
    ./$(APP_NAME)
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Running application'
  env:
    TOKEN: $(AUTH_TOKEN)